### PR TITLE
Refactor and cleanup

### PR DESCRIPTION
**Pull request by Sean-Der**
Hey @sneakyimp 
I am gonna try and go through and fix as many issues/bugs as I can find. A lot of this stuff _works_ but by accident on Linux/amd64, going to try my best to cleanup as many as these issues.

Running into a handful of issues that I just bump into by accident, if you can get a full test suite in I will really try to dig in and fix all the weird issues I can.

thanks!

### CODE REVIEW

**Comment by sneakyimp** [comment]
Firstly, thank you for your generous assistance. I'm not so sure about a couple of these changes and would like to discuss?

1) The function amf_add_var_hash is taken more or less directly from the native php function php_add_var_hash:
http://lxr.php.net/xref/PHP_5_6/ext/standard/var.c#546

You can see that function adding var_no directly to a hash table. Why did you make this a zval instead? Seems unnecessary and inefficient to me.

Also, if we change amf_add_var_hash to treat var_no as a zval, we have to alter any calls to this function to pass in a zval or we can expect bizarre behavior.

2) I see that you removed the zval_dtor(assoc_value) I added in amf_read_array. Looks like that is indeed the right move -- and this change fixes the most recent issue you reported (array ['a' => 'a'] test). However, I'm confused why we don't dtor the zval. It was my understanding this zval is "copied" by the add_assoc_zval function. Hoping you might shed a little light on what is happening there.

**Comment by Sean-Der** [comment]
1.) Other people were modifying that same hash and adding zvals to it (so had a mix of values) that works, but is confusing. So I just changed it to add zvals, and then updated the HashTable to call ptr_dtor on [destruction](https://github.com/sneakyimp/amfext/pull/5/files#diff-5858897c20e606e3c02310e036ceb716R1462) so that if the values we are adding are unused they are just deleted.

2.) I think I did a crappy job of explaining this, there was a pretty good web page about this (I think I might have sent it?) tell me if I didn't!

So when a zval is created it has a refcount of 1, the refcount says 'how many people have pointers to this value' like HashTables etc...
If the refcount falls to 0, we GC that value. zval_ptr_dtor decrements the value 1, and zval_dtor destroys the value no matter what the refcount is.

Before we had the `htStrings` HashTable that had a bunch of values later to be used for references (if a string appeared twice) . If a string appears we pluck it from the HashTable and up the refcount, however if we never pluck it we never up the refcount. 
With the change I just [added](https://github.com/sneakyimp/amfext/pull/5/files#diff-5858897c20e606e3c02310e036ceb716R1525 if a string is never plucked it is properly collected at the end. 

I think a big issue is also that my changes are sort of thrashy :/ I don't understand the code base fully and don't know when I am breaking things. When we have a full set of test data, I think it will be better!

Also, you said `make test` isn't running? Make sure to remove amfext from your current PHP install (so if you run `php -m` from the command line right now the extension should not appear) if the extension is loaded already, and then doubly loaded
by `make test` it will just skip all the tests.

**Comment by sneakyimp** [comment]
> 1.) Other people were modifying that same hash and adding zvals to it (so had a mix of values) that works, but is confusing. So I just changed it to add zvals, and then updated the HashTable to call ptr_dtor on destruction so that if the values we are adding are unused they are just deleted.

I don't follow what you are saying here. I'll state more clearly that my function emulates almost exactly the php_add_var_hash function used by the serialize function and I don't think it needs a zval. Additionally, if we change it to add zvals, I think we'll also need to change the code where we call this function, which you have not done in this PR. I'm therefore disinclined to accept the PR -- at least this aspect of it -- at least not until I understand better why you made the change.

2) Thanks for the clarification! I'll need some time to try and digest this fully. This week is really tough so far.

3) "make test" does not run due to my elaborate/different build procedure. As you may recall, I do not wish to install a development version of PHP on my workstation because the vast majority of the work that I do is coding in PHP, not writing php extensions in C. For various reasons, I would like to always execute my compiled php binary in its source folder by its full path (or possibly a partial path from the current working directory.

Now I'm not at all sure how "make test" attempts to execute the test scripts, but from what I can tell, it would appear to try and use the version of php that you have installed on your machine:

```
PHP         : /usr/bin/php 
PHP_SAPI    : cli
PHP_VERSION : 5.3.10-1ubuntu3.19
ZEND_VERSION: 2.3.0
```

Yes, I know this looks old, but it's the version installed by the ubuntu package manager on my workstation.

Is there not some way to execute 'make test' and have it use instead /home/sneakyimp/src/php-5.5.29/sapi/cli/php while using the php.ini file /home/jaith/src/php-5.5.29/php.ini ? It just seems a bit weird to have your development version of php installed as your system's default. I need a stable/production php as my default and I want to run my dev only when I'm testing, etc.

**Comment by Sean-Der** [comment]
1.) The HashTable that is being passed amf_add_var_hash during debugging I _thought_ had a mix of zvals + non-zvals, so I thought I was updating it to be all zvals. You don't need to update the calling code, it creates a zval in the function and the inserts it. Also in PHP7 you can't add arbitrary values to a HashTable. Would you like me to update the PR to go back to the old method (honestly these are all style nits, I am happy either way I just want this extension to succeed!)

2.) Sorry to hear about your week being tough :( Take some time off from this if it is stressing you out! I am always around, just tell me what helps you.

3.) There are a lot of things you could do (prefix etc..) but I would suggest using this [vagrant image](https://github.com/rlerdorf/php7dev) or just spin up a VM in VirtualBox for dedicated PHP development.

**Comment by sneakyimp** [comment]
OK I'm back on this today. Want to thank you again, Sean. Would never get this done without your encouragement and tutelage.

> 1.) The HashTable that is being passed amf_add_var_hash during debugging I thought had a mix of zvals + non-zvals, so I thought I was updating it to be all zvals. You don't need to update the calling code, it creates a zval in the function and the inserts it. Also in PHP7 you can't add arbitrary values to a HashTable. Would you like me to update the PR to go back to the old method (honestly these are all style nits, I am happy either way I just want this extension to succeed!)

OK. In the interest of making amfext easier to port to php7, I'm inclined to adopt your zval changes to amf_add_var_hash, however, I'd like to clarify what this function is doing--or try anyway, if only to help me understand better:

```
inline int amf_add_var_hash(HashTable *htVars, zval *var, void *var_old TSRMLS_DC)
```

This function checks to see if **var** has already been serialized by checking the HashTable **htVars**. **htVars** does not actually store the values previously encountered, it stores a hash derived from their memory location. If the hash derived from **var** is not found in **htVars**, then it is added. The return value of amf_add_var_hash indicates whether or not **var** was found. If **var** was in fact found in **htVars**, then the function returns FAILURE and var_old contains the index where **var** was found in **htVars**.

Having explained this to myself, I think I feel fairly comfortable applying this zval change.

**Comment by sneakyimp** [comment]
OK so I applied your changes and it does in fact break things. The reason is because this line:

```
    if (var_old && zend_hash_find(htVars, p, len, var_old) == SUCCESS) {
        return FAILURE;
    }
```

is retrieving a zval into var_old which we are returning to the calling scope. Because it is a zval and not a ulong, we end up trying to serialize not the value of var_no that we wanted to store (which is the number of elements in **htVars**) but its memory location instead -- or at least I think this is the problem.  Basically, the confusion seems to arise because we're passing a zval back to the scope from which we called amf_add_var_hash and that code is treating is as a long:

```
    if (htComplexObjects && amf_add_var_hash(htComplexObjects, *val, (void *) &prev_serialized_ref TSRMLS_CC) == FAILURE) {
        /* if we are unable to add val's hash to htComplexObjects, this means
         * we have already encountered this array before and wrote it
         * previously to htComplexObjects and its key in that array is prev_serialized_ref
         * just write prev_serialized_ref shifted left by one bit, leaving the lowest
         * bit as zero (to indicate an object reference rather than a value reference)
         * as an amf-style 29 digit int and return */
        amf_write_int(buf, (((long)*prev_serialized_ref - 1) << 1));
        return;
    }
```

**Comment by sneakyimp** [comment]
I have also tried your strz changes in the function amf_read_string but these also break things. At least this one does:

```
            if (zend_hash_next_index_insert(htStrings, (void **)&strz, sizeof(zval *), NULL) != SUCCESS) {
                php_error_docref(NULL TSRMLS_CC, E_ERROR, "Error adding string to strings hash table");
            }
```

It seems to result in garbled values. Given that we declare this:

```
zval *strz
```

It seems odd to cast strz as void*\* before passing to that macro. It's hard as hell to tell what's going on with all the macro nesting.

I moved the strz declaration and that seems fine.

removing my call to zval_ptr_dtor(strval) introduces a couple of memory leaks but serialization still works fine.

I wondered if these changes might somehow compensate/fix the memory leak:

```
zend_hash_init(&htComplexObjects, 10, NULL, ZVAL_PTR_DTOR, 0);
zend_hash_init(&htObjectTypeTraits, 10, NULL, NULL, 0);
zend_hash_init(&htStrings, 10, NULL, ZVAL_PTR_DTOR, 0);
```

However, this change causes a segfault on at least one of my tests. I will try to flesh out some more tests for you to run, but I don't really understand the structure/format of the phpt tests. I'll be looking into that today.

**Pull request closed without merging**
